# Generated by Django 3.1.6 on 2021-02-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.ManyToManyField(blank=True, default='', null=True, to='directory.Subjects'),
        ),
    ]
