# Generated by Django 3.1.6 on 2021-02-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_auto_20210214_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
