# Generated by Django 3.1.6 on 2021-02-14 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_auto_20210214_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='subject',
            new_name='subjects',
        ),
    ]
